services:
  db:
    image: mcr.microsoft.com/mssql/server:2022-latest
    platform: linux/amd64
    container_name: dotnet_sample_sql_server_db
    environment:
      SA_PASSWORD: '${MSSQL_SA_PASSWORD}'
      ACCEPT_EULA: 'Y'
      MSSQL_PID: 'Developer'
    ports:
      - '1433:1433'
    volumes:
      - ./docker/data:/var/opt/mssql
    networks:
      - app_network

  redis:
    image: redis:7.0-alpine
    container_name: dotnet_sample_redis
    ports:
      - '6379:6379'
    volumes:
      - ./docker/redis:/data
    command: redis-server --appendonly yes
    networks:
      - app_network

  api:
    build:
      context: .
      dockerfile: apps/api/Dockerfile
    platform: linux/amd64
    container_name: dotnet_sample_api_backend
    ports:
      - '8080:8080'
    environment:
      ASPNETCORE_URLS: http://+:8080
      ConnectionStrings__DefaultConnection: 'Server=db,1433;Database=${DB_NAME};User Id=sa;Password=${MSSQL_SA_PASSWORD};TrustServerCertificate=True'
      ConnectionStrings__RedisConnection: 'redis:6379'
      Jwt__Issuer: ${JWT_ISSUER}
      Jwt__Audience: ${JWT_AUDIENCE}
      Jwt__Key: ${JWT_SECRET}
    networks:
      - app_network

networks:
  app_network:
    driver: bridge
