name: dotnet-auth-api-sample
services:
  db:
    image: mcr.microsoft.com/mssql/server:2022-latest
    platform: linux/amd64
    container_name: dotnet_sample_sql_server_db
    environment:
      MSSQL_DATABASE: '${DB_NAME}'
      SA_PASSWORD: '${MSSQL_SA_PASSWORD}'
      ACCEPT_EULA: 'Y'
      MSSQL_PID: 'Developer'
    ports:
      - '1433:1433'
    volumes:
      - ./docker/data:/var/opt/mssql
    networks:
      - app_network

  redis:
    image: redis:7.0-alpine
    container_name: dotnet_sample_redis
    ports:
      - '6379:6379'
    volumes:
      - ./docker/redis:/data
    command: redis-server --appendonly yes
    networks:
      - app_network

  api:
    build:
      context: .
      dockerfile: Dockerfile
    platform: linux/amd64
    container_name: dotnet_sample_api_backend
    ports:
      - '8080:8080'
      - '8443:8443'
    environment:
      ASPNETCORE_ENVIRONMENT: ${ASPNETCORE_ENVIRONMENT}
      ASPNETCORE_URLS: ${ASPNETCORE_URLS}
      SSL_CERT_PATH: ${SSL_CERT_PATH}
      SSL_KEY_PATH: ${SSL_KEY_PATH}
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${MSSQL_SA_PASSWORD}
      DB_NAME: ${DB_NAME}
      ConnectionStrings__DefaultConnection: 'Server=db,1433;Database=${DB_NAME};User Id=sa;Password=${MSSQL_SA_PASSWORD};TrustServerCertificate=True'
      ConnectionStrings__RedisConnection: 'redis:6379'
      Jwt__Issuer: ${JWT_ISSUER}
      Jwt__Audience: ${JWT_AUDIENCE}
      Jwt__Key: ${JWT_SECRET}
      NUGET_PACKAGES: /root/.nuget/packages
    volumes:
      - .:/src:delegated
      - nuget-packages:/root/.nuget/packages
      - ../../.certificate:/https:ro
    networks:
      - app_network
    depends_on:
      - db

networks:
  app_network:
    driver: bridge

volumes:
  sqldata:
  nuget-packages:
